name: Lint and spellcheck

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Commit / Branch / Tag / SHA to checkout
        required: false
        default: ""
      python-version:
        description: Python version
        required: false
        default: "3.14"
  workflow_call:
    inputs:
      tag:
        description: Commit / Branch / Tag / SHA to checkout
        required: false
        default: ""
        type: string
      python-version:
        description: Python version
        required: false
        default: "3.14"
        type: string

permissions:
  contents: read

jobs:
  ruff:
    uses: bagofseeds/actions/.github/workflows/lint.yaml@bad7219d1cc6280a38fbcffd35ff71314a694bb9
    with:
      tag: ${{ inputs.tag }}
      python-version: ${{ inputs.python-version }}
      requirements-file: requirements-lint.txt
      lint-command: ruff check .

  spellcheck:
    uses: bagofseeds/actions/.github/workflows/lint.yaml@bad7219d1cc6280a38fbcffd35ff71314a694bb9
    with:
      tag: ${{ inputs.tag }}
      python-version: ${{ inputs.python-version }}
      requirements-file: requirements-lint.txt
      lint-command: codespell .
