name: Publish to PyPI on release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test-and-publish:
    uses: bagofseeds/actions/.github/workflows/test-and-publish.yaml@bad7219d1cc6280a38fbcffd35ff71314a694bb9
    with:
      tag: ${{ github.ref }}
      test: true
      publish: test+pypi
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
